name: Check lint, format and tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check Lint and Format
    steps:
      - uses: actions/checkout@v2
      - name: Check with rustfmt
        run: cargo fmt --all -- --check

      - name: Check with Clippy
        run: cargo clippy --workspace --tests --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Unit Tests
        run: cargo test
